# Generated by Django 5.1.1 on 2024-10-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
