# Generated by Django 5.1.1 on 2024-10-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_invoicenumber_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
