# Generated by Django 5.1.1 on 2024-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_guest_car_plate_number_guest_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='valid_id',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
