# Generated by Django 5.1.1 on 2024-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_guest_email_alter_guest_valid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
